[tool.poetry]
name = "cvpack-alkasm"
packages = [
    { include = "cvpack" },
]
version = "1.1.0"
description = "Utilities for OpenCV in Python"
authors = ["Alexander Reynolds <alex@theory.shop>"]
homepage = "https://github.com/alkasm/cvpack"
repository = "https://github.com/alkasm/cvpack"
keywords = ["cvpack", "computer vision", "cv", "opencv"]
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
include = ["py.typed"]

[tool.poetry.dependencies]
python = "^3.6"
opencv-python = "!=4.2.0.32"
IPython = {version = "~=7.16", optional = true}
numpy = "^1.19.5"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
black = "^19.10b0"
hypothesis = "^5.8.0"
IPython = "~=7.16"
mypy = "^0.790"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
