# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.api.mappings_api import MappingsApi  # noqa: E501
from dlxapi.rest import ApiException


class TestMappingsApi(unittest.TestCase):
    """MappingsApi unit test stubs"""

    def setUp(self):
        self.api = dlxapi.api.mappings_api.MappingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_spreadsheet_to_mappings(self):
        """Test case for spreadsheet_to_mappings

        Accepts upload of spreadsheet and converts data into mappings.  # noqa: E501
        """
        pass

    def test_update_mapping(self):
        """Test case for update_mapping

        Update mapping  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
