# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.models.resource_pool_created_event import ResourcePoolCreatedEvent  # noqa: E501
from dlxapi.rest import ApiException


class TestResourcePoolCreatedEvent(unittest.TestCase):
    """ResourcePoolCreatedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourcePoolCreatedEvent(self):
        """Test ResourcePoolCreatedEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dlxapi.models.resource_pool_created_event.ResourcePoolCreatedEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
