# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.models.warnings import Warnings  # noqa: E501
from dlxapi.rest import ApiException


class TestWarnings(unittest.TestCase):
    """Warnings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWarnings(self):
        """Test Warnings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dlxapi.models.warnings.Warnings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
