# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.api.notifications_api import NotificationsApi  # noqa: E501
from dlxapi.rest import ApiException


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self):
        self.api = dlxapi.api.notifications_api.NotificationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_notifications(self):
        """Test case for get_notifications

        Retrieves portfolio notifications log.  # noqa: E501
        """
        pass

    def test_reindex_notifications(self):
        """Test case for reindex_notifications

        Reindex notifications. System Administator operation.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
