# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.models.category_option_created_event import CategoryOptionCreatedEvent  # noqa: E501
from dlxapi.rest import ApiException


class TestCategoryOptionCreatedEvent(unittest.TestCase):
    """CategoryOptionCreatedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategoryOptionCreatedEvent(self):
        """Test CategoryOptionCreatedEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dlxapi.models.category_option_created_event.CategoryOptionCreatedEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
