# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.api.tags_api import TagsApi  # noqa: E501
from dlxapi.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = dlxapi.api.tags_api.TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tag(self):
        """Test case for create_tag

        Creates a new tag  # noqa: E501
        """
        pass

    def test_delete_tag(self):
        """Test case for delete_tag

        Delete a single tag  # noqa: E501
        """
        pass

    def test_get_tag(self):
        """Test case for get_tag

        Retrieves a tag  # noqa: E501
        """
        pass

    def test_get_tags_for_portfolio(self):
        """Test case for get_tags_for_portfolio

        Retrieves tags for a portfolio  # noqa: E501
        """
        pass

    def test_update_tag(self):
        """Test case for update_tag

        Update a single tag  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
