[tool.poetry]
name = "zeekshipper"
version = "0.1.0"
description = "using it:.log to parquet,and push it to minio,final back to you a .txt file with cmd-line for trino to build table."
authors = ["Mutu <mutou_nan@163.com>"]

[tool.poetry.dependencies]
python = "^3.7"
zat = "^0.4.2"
fastparquet = "^0.5.0"
pathlib = "^1.0.1"
minio = "^7.0.3"
s3fs = "^2021.4.0"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
zeekshipper = 'zeekshipper.zeeker:log_minio_trino'