[tool.poetry]
name = "django-kesha"
version = "0.1.2"
description = "Accounting Helper Django App"
authors = ["Florian Rämisch <olf@subsignal.org>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/olf42/django-kesha"

packages = [
    { include="kesha", from="." },
]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.2"
django-money = "^1.3.1"
PyYAML = "^5.4.1"
django-doma = "^0.2.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.0"
black = "^20.8b1"
pre-commit = "^2.12.0"
factory-boy = "^3.2.0"
pytest = "^6.2.3"
pytest-django = "^4.2.0"
pytest-cov = "^2.11.1"
tox = "^3.23.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
