
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-24T23:21:42+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "3d85c1cb5d16080dd63ade0dda17dc1564b10e36",
 "version": "0.2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
