[tool.poetry]
name = "cltools"
version = "0.5.0"
description = "Set of decorators of to create transform a class into a command-line tool."
authors = ["Gissehel <public-dev-cltools@gissehel.org>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/gissehel/cltools"
repository = "https://github.com/gissehel/cltools"
documentation = "https://github.com/gissehel/cltools"
keywords = ["cltools","commandline","tools","decorator"]
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Topic :: System :: Shells',
    'Topic :: Terminals',
    'Topic :: Utilities',
]

[project]
python = "^3.6"
