[tool.poetry]
name = "celery_bundle"
version = "2.0.0"
description = ""
authors = ["Alvaro Garcia <maxpowel@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
applauncher = "^2.0.0"
celery = "^5.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
