[tool.poetry]
name = "ulogcorn"
version = "0.4.0"
description = "Unify logging for a gunicorn and uvicorn application with loguru"
authors = ["欧德天.尼维森莫.纳墨迪奥 <icocoabeans@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
uvicorn = {extras = ["standard"], version = "^0.13.4"}
gunicorn = "^20.1.0"
fastapi = "^0.63.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
