
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-27T22:47:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7816cb6425797732c7b3d718db021e784e7864f",
 "version": "0.8.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
