# Generated by Django 3.2 on 2021-04-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doma", "0004_alter_document_replaces"),
        ("kesha", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booking",
                to="doma.document",
            ),
        ),
    ]
