
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-27T12:06:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea32fd5d3410e6ff8c8c1d56813f1f4a45d21b9d",
 "version": "2447"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
