[tool.poetry]
name = "new-relic-logger-for-python"
version = "0.1.7"
description = "Push logs into New Relic using standard python logger asynchronously."
authors = ["Andrés Peñaloza <andres.penaloza@xintec.cl>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "newrelic_logger" },
]
[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
newrelic = "^6.2.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"