[tool.poetry]
name = "npmrc2yarnrc"
version = "0.3.0"
description = ""
authors = ["Willem Thiart <himself@willemthiart.com>"]

[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^5.4.1"
mergedeep = "^1.3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
npmrc2yarnrc = "npmrc2yarnrc.__init__:merge_iotex_npmrc_into_yarnrc"
