[tool.poetry]
name = "omniblack.model"
version = "0.1.1"
description = ""
authors = ["Terry Patterson <Terryp@wegrok.net>"]
license = "AGPL-3.0-or-later"
packages = [
    {include = 'omniblack/model/*'}
]

[tool.poetry.dependencies]
python = "^3.9"
rx = "3.1.1"
"ruamel.yaml" = {version="^0.16.12", optional = true}
anyio = "3.0.0"
sniffio = "^1.2.0"
trio = {version = "^0.18.0", optional = true}
more_itertools = "^8.7.0"
humanize = "^3.4.1"
toml = {version = "^0.10.2", optional = true}

[tool.poetry.extras]
toml = ['toml']
yaml = ['ruamel.yaml']

[tool.poetry.dev-dependencies]
bpython = "^0.21"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
