[build-system]
requires = [ "setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
/)
'''

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{36,37,38}-django2_2

[testenv]
deps =
  bleach
  django2_2: Django>=2.2,<2.3
  djangorestframework
commands = python user_feedback.py test
"""
