
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-26T17:40:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "16d2f19cb6282629ba169a6f676be4ee758f7109",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
