
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "40ba4bd5c8b91754aa73e638ed984ab9657847cd",
 "version": "0.9.0-alpha.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
