[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "timedfunc"
author = "Daniel Pauli"
author-email = "dapaulid@gmail.com"
home-page = "https://github.com/dapaulid/timedfunc"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"
