
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-22T13:38:00-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "86cc4c654b7d243ec7e95cc624a6bfd2d6f2366a",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
