[tool.poetry]
name = "cabin"
version = "0.1.1"
description = "Common code for log-cabin-data projects"
authors = ["Finn Welsford-Ackroyd <finnwa24@gmail.com>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
marshmallow-dataclass = "^8.4.1"
marshmallow = "^3.11.1"
pandas = "^1.2.4"
python-dateutil = "^2.8.1"
flatten-json = "^0.1.13"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
pytest = "^6.2.3"
pytest-mock = "^3.5.1"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true
