
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-23T15:01:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "818c4bcca398aa4b9d0d2d4d4c5aec9302bc5eb4",
 "version": "v0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
