
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-23T13:35:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9ac03a474741380b6771f6a2602b671d7b4bb69",
 "version": "4.5.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
