[project]
name = "trick"
version = "0.1.0"
description = "A collection of some helper functions"
dependencies = []
requires-python = ">=3.9"
dynamic = [ "classifiers",]
readme = "README.md"
[[project.authors]]
name = "Elliot"
email = "hack00mind@gmail.com"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/Eliot00/python-trick"

[tool.pdm.dev-dependencies]
dev = []
test = [ "pytest~=6.2",]
