#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='turing_calculator',
      version='0.1.0',
      description='Simple calculator in python',
      author='Keelan Jordan',
      author_email='keelan@keelanjordan.com',
      url='https://github.com/keelanjordan/turing_calculator-py',
      py_modules=['turing_calculator'],
     )
