[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project]
name = "flake8-tabs"
description = "Tab (or Spaces) indentation style checker for flake"
version = "2.3.2"
license = "LGPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [ "flake8 ~= 3.0", "editorconfig ~= 0.12.0",]
classifiers = [ "Framework :: Flake8", "Intended Audience :: Developers", "Development Status :: 4 - Beta", "Topic :: Software Development :: Libraries :: Python Modules", "Topic :: Software Development :: Quality Assurance", "Operating System :: OS Independent",]
dynamic = [ "classifiers", "version",]
[[project.authors]]
name = "Alexander Schlarb"
email = "alexander@ninetailed.ninja"

[project.optional-dependencies]
doc = [ "sphinx",]

[project.urls]
repository = "https://gitlab.com/ntninja/flake8-tabs/-/tree/master/"
"Issue Tracker" = "https://gitlab.com/ntninja/flake8-tabs/issues/"

[tool.isort]
atomic = true
color_output = true
lines_after_imports = 2
force_single_line = true
remove_redundant_aliases = true
skip_glob = [ "__pypackages__/**",]

[project.entry-points."flake8.extension"]
"tabs.core" = "flake8_tabs:Config"
"tabs.blank-lines" = "flake8_tabs:BlankLinesChecker"
"tabs.indentation" = "flake8_tabs:IndentationChecker"

[tool.pdm.scripts]
lint = "flake8"

[tool.pdm.dev-dependencies]
dev = [ "flake8-formatter-junit-xml", "flake8-isort", "pytest", "pytest-cov",]
