# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.api.default_api import DefaultApi  # noqa: E501
from dlxapi.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = dlxapi.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_category_option(self):
        """Test case for create_category_option

        Creates a new category  # noqa: E501
        """
        pass

    def test_create_category_options(self):
        """Test case for create_category_options

        Creates new category options  # noqa: E501
        """
        pass

    def test_delete_category_option(self):
        """Test case for delete_category_option

        Delete a single category option  # noqa: E501
        """
        pass

    def test_get_category_option(self):
        """Test case for get_category_option

        Retrieves a category  # noqa: E501
        """
        pass

    def test_get_category_options_for_field(self):
        """Test case for get_category_options_for_field

        Retrieves categories for a field  # noqa: E501
        """
        pass

    def test_update_category_option(self):
        """Test case for update_category_option

        Update a single category  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
