# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.models.resource_pool_budget_amount import ResourcePoolBudgetAmount  # noqa: E501
from dlxapi.rest import ApiException


class TestResourcePoolBudgetAmount(unittest.TestCase):
    """ResourcePoolBudgetAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourcePoolBudgetAmount(self):
        """Test ResourcePoolBudgetAmount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dlxapi.models.resource_pool_budget_amount.ResourcePoolBudgetAmount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
