# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.models.sub_portfolio_removed_event import SubPortfolioRemovedEvent  # noqa: E501
from dlxapi.rest import ApiException


class TestSubPortfolioRemovedEvent(unittest.TestCase):
    """SubPortfolioRemovedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubPortfolioRemovedEvent(self):
        """Test SubPortfolioRemovedEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dlxapi.models.sub_portfolio_removed_event.SubPortfolioRemovedEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
