# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.models.mail import Mail  # noqa: E501
from dlxapi.rest import ApiException


class TestMail(unittest.TestCase):
    """Mail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMail(self):
        """Test Mail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dlxapi.models.mail.Mail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
