# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinator/coordinator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coordinator/coordinator.proto',
  package='cit_fl_proto.coordinator',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x63oordinator/coordinator.proto\x12\x18\x63it_fl_proto.coordinator\"%\n\x11RendezvousRequest\x12\x10\n\x08\x41piToken\x18\x01 \x01(\t\"\xbe\x01\n\x12RendezvousResponse\x12T\n\x0bParticipate\x18\x01 \x01(\x0e\x32?.cit_fl_proto.coordinator.RendezvousResponse.ParticipationState\x12\x15\n\rParticipantId\x18\x02 \x01(\t\";\n\x12ParticipationState\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x00\x12\t\n\x05LATER\x10\x01\x12\x0c\n\x08REJECTED\x10\x02\"\x12\n\x10HeartbeatRequest\"\xab\x01\n\x11HeartbeatResponse\x12H\n\x05State\x18\x01 \x01(\x0e\x32\x39.cit_fl_proto.coordinator.HeartbeatResponse.LearningState\x12\x13\n\x0bRoundNumber\x18\x02 \x01(\r\"7\n\rLearningState\x12\x0b\n\x07STANDBY\x10\x00\x12\x0b\n\x07TRAINIG\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x02\"\x1b\n\x19StartTrainingRoundRequest\"T\n\x1aStartTrainingRoundResponse\x12\x13\n\x0bRoundNumber\x18\x01 \x01(\r\x12\x0e\n\x06\x65pochs\x18\x02 \x01(\r\x12\x11\n\tEpochBase\x18\x03 \x01(\r\"C\n\x17\x45ndTrainingRoundRequest\x12\x11\n\tWeightsId\x18\x01 \x01(\t\x12\x15\n\rNumberSamples\x18\x02 \x01(\x04\"\x1a\n\x18\x45ndTrainingRoundResponse2\xd7\x03\n\x12\x43oordinatorService\x12i\n\nRendezvous\x12+.cit_fl_proto.coordinator.RendezvousRequest\x1a,.cit_fl_proto.coordinator.RendezvousResponse\"\x00\x12\x66\n\tHeartbeat\x12*.cit_fl_proto.coordinator.HeartbeatRequest\x1a+.cit_fl_proto.coordinator.HeartbeatResponse\"\x00\x12y\n\nStartRound\x12\x33.cit_fl_proto.coordinator.StartTrainingRoundRequest\x1a\x34.cit_fl_proto.coordinator.StartTrainingRoundResponse\"\x00\x12s\n\x08\x45ndRound\x12\x31.cit_fl_proto.coordinator.EndTrainingRoundRequest\x1a\x32.cit_fl_proto.coordinator.EndTrainingRoundResponse\"\x00\x62\x06proto3'
)



_RENDEZVOUSRESPONSE_PARTICIPATIONSTATE = _descriptor.EnumDescriptor(
  name='ParticipationState',
  full_name='cit_fl_proto.coordinator.RendezvousResponse.ParticipationState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCEPTED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LATER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REJECTED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=230,
  serialized_end=289,
)
_sym_db.RegisterEnumDescriptor(_RENDEZVOUSRESPONSE_PARTICIPATIONSTATE)

_HEARTBEATRESPONSE_LEARNINGSTATE = _descriptor.EnumDescriptor(
  name='LearningState',
  full_name='cit_fl_proto.coordinator.HeartbeatResponse.LearningState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STANDBY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRAINIG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=428,
  serialized_end=483,
)
_sym_db.RegisterEnumDescriptor(_HEARTBEATRESPONSE_LEARNINGSTATE)


_RENDEZVOUSREQUEST = _descriptor.Descriptor(
  name='RendezvousRequest',
  full_name='cit_fl_proto.coordinator.RendezvousRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ApiToken', full_name='cit_fl_proto.coordinator.RendezvousRequest.ApiToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=96,
)


_RENDEZVOUSRESPONSE = _descriptor.Descriptor(
  name='RendezvousResponse',
  full_name='cit_fl_proto.coordinator.RendezvousResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Participate', full_name='cit_fl_proto.coordinator.RendezvousResponse.Participate', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ParticipantId', full_name='cit_fl_proto.coordinator.RendezvousResponse.ParticipantId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RENDEZVOUSRESPONSE_PARTICIPATIONSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=289,
)


_HEARTBEATREQUEST = _descriptor.Descriptor(
  name='HeartbeatRequest',
  full_name='cit_fl_proto.coordinator.HeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=309,
)


_HEARTBEATRESPONSE = _descriptor.Descriptor(
  name='HeartbeatResponse',
  full_name='cit_fl_proto.coordinator.HeartbeatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='State', full_name='cit_fl_proto.coordinator.HeartbeatResponse.State', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RoundNumber', full_name='cit_fl_proto.coordinator.HeartbeatResponse.RoundNumber', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HEARTBEATRESPONSE_LEARNINGSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=483,
)


_STARTTRAININGROUNDREQUEST = _descriptor.Descriptor(
  name='StartTrainingRoundRequest',
  full_name='cit_fl_proto.coordinator.StartTrainingRoundRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=512,
)


_STARTTRAININGROUNDRESPONSE = _descriptor.Descriptor(
  name='StartTrainingRoundResponse',
  full_name='cit_fl_proto.coordinator.StartTrainingRoundResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RoundNumber', full_name='cit_fl_proto.coordinator.StartTrainingRoundResponse.RoundNumber', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='epochs', full_name='cit_fl_proto.coordinator.StartTrainingRoundResponse.epochs', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EpochBase', full_name='cit_fl_proto.coordinator.StartTrainingRoundResponse.EpochBase', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=598,
)


_ENDTRAININGROUNDREQUEST = _descriptor.Descriptor(
  name='EndTrainingRoundRequest',
  full_name='cit_fl_proto.coordinator.EndTrainingRoundRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='WeightsId', full_name='cit_fl_proto.coordinator.EndTrainingRoundRequest.WeightsId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NumberSamples', full_name='cit_fl_proto.coordinator.EndTrainingRoundRequest.NumberSamples', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=667,
)


_ENDTRAININGROUNDRESPONSE = _descriptor.Descriptor(
  name='EndTrainingRoundResponse',
  full_name='cit_fl_proto.coordinator.EndTrainingRoundResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=669,
  serialized_end=695,
)

_RENDEZVOUSRESPONSE.fields_by_name['Participate'].enum_type = _RENDEZVOUSRESPONSE_PARTICIPATIONSTATE
_RENDEZVOUSRESPONSE_PARTICIPATIONSTATE.containing_type = _RENDEZVOUSRESPONSE
_HEARTBEATRESPONSE.fields_by_name['State'].enum_type = _HEARTBEATRESPONSE_LEARNINGSTATE
_HEARTBEATRESPONSE_LEARNINGSTATE.containing_type = _HEARTBEATRESPONSE
DESCRIPTOR.message_types_by_name['RendezvousRequest'] = _RENDEZVOUSREQUEST
DESCRIPTOR.message_types_by_name['RendezvousResponse'] = _RENDEZVOUSRESPONSE
DESCRIPTOR.message_types_by_name['HeartbeatRequest'] = _HEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['HeartbeatResponse'] = _HEARTBEATRESPONSE
DESCRIPTOR.message_types_by_name['StartTrainingRoundRequest'] = _STARTTRAININGROUNDREQUEST
DESCRIPTOR.message_types_by_name['StartTrainingRoundResponse'] = _STARTTRAININGROUNDRESPONSE
DESCRIPTOR.message_types_by_name['EndTrainingRoundRequest'] = _ENDTRAININGROUNDREQUEST
DESCRIPTOR.message_types_by_name['EndTrainingRoundResponse'] = _ENDTRAININGROUNDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RendezvousRequest = _reflection.GeneratedProtocolMessageType('RendezvousRequest', (_message.Message,), {
  'DESCRIPTOR' : _RENDEZVOUSREQUEST,
  '__module__' : 'coordinator.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:cit_fl_proto.coordinator.RendezvousRequest)
  })
_sym_db.RegisterMessage(RendezvousRequest)

RendezvousResponse = _reflection.GeneratedProtocolMessageType('RendezvousResponse', (_message.Message,), {
  'DESCRIPTOR' : _RENDEZVOUSRESPONSE,
  '__module__' : 'coordinator.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:cit_fl_proto.coordinator.RendezvousResponse)
  })
_sym_db.RegisterMessage(RendezvousResponse)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'coordinator.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:cit_fl_proto.coordinator.HeartbeatRequest)
  })
_sym_db.RegisterMessage(HeartbeatRequest)

HeartbeatResponse = _reflection.GeneratedProtocolMessageType('HeartbeatResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATRESPONSE,
  '__module__' : 'coordinator.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:cit_fl_proto.coordinator.HeartbeatResponse)
  })
_sym_db.RegisterMessage(HeartbeatResponse)

StartTrainingRoundRequest = _reflection.GeneratedProtocolMessageType('StartTrainingRoundRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTTRAININGROUNDREQUEST,
  '__module__' : 'coordinator.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:cit_fl_proto.coordinator.StartTrainingRoundRequest)
  })
_sym_db.RegisterMessage(StartTrainingRoundRequest)

StartTrainingRoundResponse = _reflection.GeneratedProtocolMessageType('StartTrainingRoundResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTTRAININGROUNDRESPONSE,
  '__module__' : 'coordinator.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:cit_fl_proto.coordinator.StartTrainingRoundResponse)
  })
_sym_db.RegisterMessage(StartTrainingRoundResponse)

EndTrainingRoundRequest = _reflection.GeneratedProtocolMessageType('EndTrainingRoundRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENDTRAININGROUNDREQUEST,
  '__module__' : 'coordinator.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:cit_fl_proto.coordinator.EndTrainingRoundRequest)
  })
_sym_db.RegisterMessage(EndTrainingRoundRequest)

EndTrainingRoundResponse = _reflection.GeneratedProtocolMessageType('EndTrainingRoundResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENDTRAININGROUNDRESPONSE,
  '__module__' : 'coordinator.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:cit_fl_proto.coordinator.EndTrainingRoundResponse)
  })
_sym_db.RegisterMessage(EndTrainingRoundResponse)



_COORDINATORSERVICE = _descriptor.ServiceDescriptor(
  name='CoordinatorService',
  full_name='cit_fl_proto.coordinator.CoordinatorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=698,
  serialized_end=1169,
  methods=[
  _descriptor.MethodDescriptor(
    name='Rendezvous',
    full_name='cit_fl_proto.coordinator.CoordinatorService.Rendezvous',
    index=0,
    containing_service=None,
    input_type=_RENDEZVOUSREQUEST,
    output_type=_RENDEZVOUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Heartbeat',
    full_name='cit_fl_proto.coordinator.CoordinatorService.Heartbeat',
    index=1,
    containing_service=None,
    input_type=_HEARTBEATREQUEST,
    output_type=_HEARTBEATRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartRound',
    full_name='cit_fl_proto.coordinator.CoordinatorService.StartRound',
    index=2,
    containing_service=None,
    input_type=_STARTTRAININGROUNDREQUEST,
    output_type=_STARTTRAININGROUNDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndRound',
    full_name='cit_fl_proto.coordinator.CoordinatorService.EndRound',
    index=3,
    containing_service=None,
    input_type=_ENDTRAININGROUNDREQUEST,
    output_type=_ENDTRAININGROUNDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATORSERVICE)

DESCRIPTOR.services_by_name['CoordinatorService'] = _COORDINATORSERVICE

# @@protoc_insertion_point(module_scope)
