[tool.poetry]
name = "spotiapi"
version = "2.0.3"
description = "A small asynchronous Wrapper for Spotify Web API."
authors = ["Aleksey Demchenkov <admin@julheer.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
http3 = "^0.6.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
