"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .mining_pb2 import *
class ArgumentMiningServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    def Entailment(self,
        request: global___EntailmentRequest,
    ) -> global___EntailmentResponse: ...


class ArgumentMiningServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Entailment(self,
        request: global___EntailmentRequest,
        context: grpc.ServicerContext,
    ) -> global___EntailmentResponse: ...


def add_ArgumentMiningServiceServicer_to_server(servicer: ArgumentMiningServiceServicer, server: grpc.Server) -> None: ...
