
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='drf-api-checker',
    version='0.11.0',
    python_requires='==3.*,>=3.6.0',
    author='sax',
    author_email='s.apostolico@gmail.com',
    license='MIT',
    packages=['drf_api_checker'],
    package_dir={"": "src"},
    package_data={},
    install_requires=['django', 'djangorestframework==3.*,>=3.10.0', 'pytz==2019.*,>=2019.3.0'],
    extras_require={"dev": ["django-webtest==1.*,>=1.9.0", "factory-boy==2.*,>=2.12.0", "pdbpp==0.*,>=0.10.2", "pyfakefs==3.*,>=3.7.0", "pytest-cov==2.*,>=2.8.0", "pytest-django==3.*,>=3.7.0", "pytest-echo==1.*,>=1.6.0", "pytest-pythonpath==0.*,>=0.7.3", "sphinx==3.*,>=3.2.1", "tox-poetry[poetry]==0.*,>=0.3.0"]},
)
