[tool.poetry]
name = "whathappened"
version = "1.0.0"
description = "A changelog generator using simply structured git commit messages."
authors = ["Rollcloud <rollcloud@gmail.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.6"
click = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-reportlog = "*"
pytest-watch = "*"
versioneer = "*"
black = "*"
flake8 = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
