
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-22T14:59:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8d22e32a9c51233e6e13da8052cd0767fd1c3f1",
 "version": "6.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
