# Generated by Django 3.2 on 2021-04-25 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doma", "0004_alter_document_replaces"),
        ("kesha", "0003_auto_20210421_1552"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="document",
        ),
        migrations.CreateModel(
            name="BookingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="kesha.booking",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="doma.document",
                    ),
                ),
            ],
        ),
    ]
