# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2021-04-26 14:51:41.304845
__version__ = '3.1.1'