
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-27T19:21:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3194550df6beac41da9db4338add5466cb539478",
 "version": "2.6.0-alpha.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
