# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MirrorRegistriesCaConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mirror_registries_config': 'MirrorRegistriesConfig',
        'ca_config': 'str'
    }

    attribute_map = {
        'mirror_registries_config': 'mirror_registries_config',
        'ca_config': 'ca_config'
    }

    def __init__(self, mirror_registries_config=None, ca_config=None):  # noqa: E501
        """MirrorRegistriesCaConfig - a model defined in Swagger"""  # noqa: E501

        self._mirror_registries_config = None
        self._ca_config = None
        self.discriminator = None

        if mirror_registries_config is not None:
            self.mirror_registries_config = mirror_registries_config
        if ca_config is not None:
            self.ca_config = ca_config

    @property
    def mirror_registries_config(self):
        """Gets the mirror_registries_config of this MirrorRegistriesCaConfig.  # noqa: E501

        configuration of registries conf  # noqa: E501

        :return: The mirror_registries_config of this MirrorRegistriesCaConfig.  # noqa: E501
        :rtype: MirrorRegistriesConfig
        """
        return self._mirror_registries_config

    @mirror_registries_config.setter
    def mirror_registries_config(self, mirror_registries_config):
        """Sets the mirror_registries_config of this MirrorRegistriesCaConfig.

        configuration of registries conf  # noqa: E501

        :param mirror_registries_config: The mirror_registries_config of this MirrorRegistriesCaConfig.  # noqa: E501
        :type: MirrorRegistriesConfig
        """

        self._mirror_registries_config = mirror_registries_config

    @property
    def ca_config(self):
        """Gets the ca_config of this MirrorRegistriesCaConfig.  # noqa: E501

        string containing CA or CA bundle for mirrored registries  # noqa: E501

        :return: The ca_config of this MirrorRegistriesCaConfig.  # noqa: E501
        :rtype: str
        """
        return self._ca_config

    @ca_config.setter
    def ca_config(self, ca_config):
        """Sets the ca_config of this MirrorRegistriesCaConfig.

        string containing CA or CA bundle for mirrored registries  # noqa: E501

        :param ca_config: The ca_config of this MirrorRegistriesCaConfig.  # noqa: E501
        :type: str
        """

        self._ca_config = ca_config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MirrorRegistriesCaConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MirrorRegistriesCaConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
