
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "branch": "rc/maintenance",
 "dirty": false,
 "error": null,
 "full-revisionid": "7054a726bb3dc363a98ec6944b24e07879bb389b",
 "version": "1.6.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
