
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-22T19:44:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c6095852042e5d6adf253a784e444708f5ab5aa",
 "version": "0.8.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
