[tool.poetry]
name = "cifrazia-django-jet"
version = "1.1.4"
description = "Django-jet fork with Django@3.0+ support"
authors = ["Bogdan Parfenov <adam.brian.bright@gmail.com>"]
license = "AGPLv3"

[tool.poetry.dependencies]
python = "~3.8"
Django = "^3.2"
six = "^1.15.0"

[tool.poetry.dev-dependencies]
twine = "^3.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
