[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "domplotlib"
version = "0.3.0"
description = "Dom's extensions to matplotlib"
readme = "README.rst"
keywords = [ "matplotlib", "plotting", "visualisation",]
dynamic = []
dependencies = [
    "cawdrey>=0.3.0",
    "domdf-python-tools>=1.7.0",
    'matplotlib==3.2.2; platform_machine == "aarch64" and python_version == "3.6"',
    'matplotlib<3.4.0,>=3.2.2; platform_machine != "aarch64" or python_version > "3.6"',
    "typing-extensions>=3.7.4.3",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Matplotlib",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.6"

[[project.authors]]
name = "Dominic Davis-Foster"
email = "dominic@davis-foster.co.uk"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/domdfcoding/domplotlib"
"Issue Tracker" = "https://github.com/domdfcoding/domplotlib/issues"
"Source Code" = "https://github.com/domdfcoding/domplotlib"
Documentation = "https://domplotlib.readthedocs.io/en/latest"

[tool.whey]
base-classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Matplotlib",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
python-versions = [ "3.6", "3.7", "3.8", "3.9",]
python-implementations = [ "CPython",]
platforms = [ "Windows", "macOS", "Linux",]
license-key = "MIT"
additional-files = [ "include domplotlib/styles/domdf.mplstyle",]

[tool.mkrecipe]
conda-channels = [ "domdfcoding",]
extras = "all"
