#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['plaw']

package_data = \
{'': ['*']}

install_requires = \
['requests', 'pytz']

setup(name='plaw',
      version='0.1.2',
      description='A simple wrapper for the Lightspeed API',
      author='Holden Nelson',
      author_email='holden.nathaniel.nelson@gmail.com',
      url='https://github.com/holden-nelson/plaw',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
