
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-23T16:40:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "90e9425fc517375cc2382489bdf0d8a482c8f857",
 "version": "1.5.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
