#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['optimal_pytorch',
 'optimal_pytorch.coin_betting',
 'optimal_pytorch.coin_betting.torch',
 'optimal_pytorch.test_functions']

package_data = \
{'': ['*']}

setup(name='optimal_pytorch',
      version='0.1.0',
      description=':mod:`optimal_pytorch` is a package implementing various coin-betting algorithms,',
      author='Nicolò Campolongo, Vibhu Bhatia, Zhenxun Zhuang',
      author_email='nico.campolongo@gmail.com',
      url='https://github.com/bremen79/optimal-pytorch/',
      packages=packages,
      package_data=package_data,
     )
