
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-26T23:11:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "709ac45ca6965a55703aa9a0fc06db25bbcf769d",
 "version": "3.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
