[tool.poetry]
name = "kapla-cli"
version = "3.1.0"
description = ""
authors = ["Guillaume Charbonnier <guillaume.charbonnier@araymond.com>"]
packages = [{ include = "kapla" }]

[tool.poetry.dependencies]
python = "^3.8"
kapla-cli-core = "^3.1.0"
commitizen = "^2.14.2"
colorama = "^0.4.4"
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
black = "^20.8b1"
flake8 = "^3.9.0"
isort = "^5.8.0"
mypy = "^0.812"
pre-commit = "^2.12.0"
twine = "^3.4.1"

[tool.poetry.dev-dependencies]
kapla-cli-core = { path = "../core/" }
colorama = "^0.4.4"

[tool.poetry.scripts]
k = "kapla.cli.app:app"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
