
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-23T14:25:25+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b81ea7df08693fdcd602f4084bfe294265686325",
 "version": "2.0.73.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
