name: Test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * *'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Test with pytest
      if: always()
      run: cd $GITHUB_WORKSPACE && ./pytest
      env:
        PYTHONUNBUFFERED: 1
