
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-21T09:20:25-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b584219faa3026650517ec5e5986981d84fb3ca3",
 "version": "0.0.88"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
