
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-23T17:57:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b28570be0371976205b6b4c1d88c3b95281a3dbf",
 "version": "0.8.279"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
