# YOLO model
yolo_model:
  model_dir: models/
  anchors_path: models/yolov3_anchors.txt
  classes_path: models/yolov3_data_classes.txt
  train_data_dir : training_data/yolo
  score: 0.25
  iou: 0.45
  gpu_num: 1
  model_image_height: 416
  model_image_width: 416
  batch_size: 32
  epochs: 11
  val_split: 0.3

# Classification model
classify_model:
  model_dir: models/
  model_image_height: 180
  model_image_width: 180
  classes: ['dump', 'no_dump']
  train_data_dir : training_data/classifier
  batch_size: 32
  epochs: 20
  val_split: 0.2

# Tesseract digit recognition model
tesseract_models:
  model_dir: models/
  lang: digits_latest
  oem: 3
  psm: 8