
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-27T19:32:34+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "dee940463f39f7c2a40ac4fbf84e27b8becf60f7",
 "version": "0.1.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
