[tool.poetry]
name = "sysq"
version = "1.7.0"
description = "demo query sys functions"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"

#[tool.poetry.dev-dependencies]
#black = "^20.8b1"
#isort = "^5.8.0"

[tool.poetry.scripts]
sysq = "sysq.core:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
