---

- hosts: all
  pre_tasks:
    - name: Set project path fact
      set_fact:
        tripleo_ipa_project_path: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/x/tripleo-ipa'].src_dir }}"

    - name: Ensure output dirs
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs"
        state: directory

    - name: Ensure pip is available
      include_role:
        name: ensure-pip

    - name: Ensure a recent version of pip is installed in virtualenv
      pip:
        name: "pip>=19.1.1"
        virtualenv: "{{ ansible_user_dir }}/test-python"
        virtualenv_command: "{{ ensure_pip_virtualenv_command }}"

    - name: Setup test-python
      pip:
        requirements: "{{ tripleo_ipa_project_path }}/molecule-requirements.txt"
        virtualenv: "{{ ansible_user_dir }}/test-python"
        virtualenv_command: "{{ ensure_pip_virtualenv_command }}"
        virtualenv_site_packages: true

    - name: Make sure tox is installed in test-python virtualenv
      pip:
        name: tox
        virtualenv: "{{ ansible_user_dir }}/test-python"

    - name: Display test-python virtualenv package versions
      shell: |-
        . {{ ansible_user_dir }}/test-python/bin/activate
        pip freeze

    # NOTE(cloudnull): This is being done because docker is not supported on RHEL-8
    #                  and tests within this repo still require docker.
    - name: Install gpg/container.io rpm
      become: true
      block:
        - name: Import GPG key from docker.com
          rpm_key:
            state: present
            key: https://download.docker.com/linux/centos/gpg
        - name: Manually install containerd.io
          package:
            name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
      when:
        - (ansible_distribution_major_version | int) >= 8
  roles:
    # docker is needed by multiple molecule scenarios
    - role: ensure-docker
