{% set name = "microbeannotator" %}
{% set version = "2.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4887cbf773c273363c9337dd479569b7be70c7731bb0bcc7b06244c92a644b51

build:
  number: 0
  entry_points:
    - microbeannotator = microbeannotator:main
    - microbeannotator_db_builder = microbeannotator_db_builder:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - setuptools_scm
    - setuptools
  host:
    - pip
    - python=3.7.5
    - setuptools
    - setuptools_scm
  run:
    - biopython
    - blast ==2.11.0
    - diamond ==2.0.9
    - python ==3.7.5
    - pywget ==3.2
    - sword ==1.0.4
    - pandas ==1.2.4
    - matplotlib ==3.4.1
    - seaborn ==0.11.1
    - psutil ==5.8.0

test:
  commands:
    - microbeannotator --help
    - microbeannotator_db_builder --help

about:
  home: "https://github.com/cruizperez/MicrobeAnnotator"
  license: Artistic Licence 2.0
  license_file: LICENSE
  summary: "A user friendly microbe genome annotation tool"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - cruizperez
