name = 'django_materialize_nav'
version = '1.2.0'
description = 'Django materialize css support.'
url = 'https://github.com/justengel-django/django_materialize_nav'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
