
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-23T14:03:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "58900fb69b54b63ddfdafe792810ef9ec9ea344b",
 "version": "v0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
