[tool.poetry]
name = "pyposeidon"
version = "0.5.2"
description = "Framework for Sea Level Hydrodynamic simulations"
authors = [
    "George Breyiannis <breyiannis@gmail.com>",
    "Panos Mavrogiorgos <pmav99@gmail.com>"
]
readme = "README.md"
homepage = "https://github.com/ec-jrc/pyposeidon"
keywords = [
    "Hydrodynamic",
    "Sea",
    "Simulation",
    "Visualization",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    'License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)',
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    'Topic :: Scientific/Engineering :: Atmospheric Science',
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Hydrology",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Libraries",
]

[tool.poetry.dependencies]
python = ">=3.7, <3.10"
numpy = "^1.20.1"
rasterio = "^1.2.0"
matplotlib = "^3.3.4"
seaborn = "^0.11.1"
dask = "^2021.2.0"
xarray = "^0.16.2"
geopandas = "^0.8.2"
tqdm = "^4.58.0"
pyresample = "^1.17.0"
pygeos = "^0.9"
gmsh = "^4.7.1"
f90nml = "^1.2"
Cartopy = "^0.18.0"
requests = "^2.25.1"
holoviews = "^1.14.1"
geoviews = "^1.8.1"
datashader = "^0.12.0"
hvplot = "^0.7.0"
netCDF4 = "^1.5.6"
colorlog = "^4.7.2"
cfgrib = "^0.9.8"
eccodes = "^1.1.0"
Shapely = "^1.7.1"
scipy = "^1.6.1"
panel = "^0.10.3"
moviepy = "^1.0.3"
branca = "^0.4.2"
ipython = "^7.20.0"
llvmlite = "^0.36.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pytest-xdist = "^2.2.1"
bump2version = "^1.0.1"
mkdocs = "^1.1.2"
mkdocs-material = "^7.0.6"
pymdown-extensions = "^8.1.1"
mkdocstrings = "^0.15.0"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --verbose --showlocals --tb=short --cov=pyposeidon --cov-report term-missing"
testpaths = [
    "tests",
]
filterwarnings = [
    'ignore:`np.*` is a deprecated alias for .* `np.*`.*:DeprecationWarning',
]
markers = [
    "schism: mark a test as a Schism based test. Needs --runschism to run",
    "delft: mark a test as a Delft3D based test. Needs --rundelft to run",
    "slow: mark a test as a slow one. Needs --runslow to run",
]

[tool.black]
line-length = 119
target-version = ['py38']
