
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-23T14:38:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1fb099954acc236e77deb7de86f147bfba689b37",
 "version": "1.5.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
