[tool.poetry]
name = "secondmer"
version = "1.0.1"
description = "SecondMer MILLIseconds. secondmer.start(100). Now library free!"
authors = ["TikOt Studio <tikotstudio@yandex.ru>"]
license = "TPL"

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
