
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "db5e9a4379be6aaf65defd420086bc8bb91a1d09",
 "version": "0.5.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
