[tool.poetry]
name = "hltv-api"
version = "0.1.0"
description = ""
authors = ["Daniel van Flymen <vanflymen@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
beautifulsoup4 = "^4.9.3"
aiohttp = "^3.7.4"
lxml = "^4.6.2"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^7.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
