[tool.poetry]
name = "tfplots"
version = "0.1.1"
description = "Utilities for quickly plotting logged tensorflow data"
authors = ["Andy Jackson <amjack100@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
altair = "^4.1.0"
altair-saver = "^0.5.0"
pandas = "^1.2.4"
matplotlib = "^3.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
