[build-system]
build-backend    = "flit_core.buildapi"
requires         = [
    "flit_core >=2,<4"
]

[tool.flit.metadata]
module           = "flask_wifiqr"
author           = "Flip Hess"
author-email     = "flip@fliphess.com"
home-page        = "https://github.com/fliphess/wifiqr"

description-file = "README.md"

requires-python  = ">=3.7"
requires         = [
    "Flask",
    "Flask-QRcode",
]

classifiers      = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.flit.metadata.requires-extra]
test             = [
    "pytest",
    "pytest-cov",
    "pyproject-flake8",
]

[tool.flake8]
max-line-length  = 250
extend-ignore    = "E203,"
max-complexity   = 10

