[tool.poetry]
name = "kubernetesclustermonitor"
version = "0.1.0"
description = ""
authors = ["kkugler <kaikugler@gmx.de>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^7.1.2"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
