[tool.poetry]
name = "grilled-common"
version = "0.1.6"
description = ""
authors = ["hans <dxzenghan@163.com>"]
packages = [
    { include = "grilled", from = "src" }
]

[[tool.poetry.source]]
name = "tuna-tsinghua"
default = false
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.8.1"
logging = "^0.4.9.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
