
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-27T21:41:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca88ad5d556a730090e81bb849fb6f491a1dd601",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
