from hestia_earth.models.utils.contant import ATOMIC_WEIGHT_CONVERSIONS

COEFF_NH3NOX_N20 = 0.01 * ATOMIC_WEIGHT_CONVERSIONS['Conv_Mol_N2ON_N2O']
COEFF_NO3N_N20 = 0.0075 * ATOMIC_WEIGHT_CONVERSIONS['Conv_Mol_N2ON_N2O']
COEFF_NO3N_N03 = ATOMIC_WEIGHT_CONVERSIONS['Conv_Mol_NO3N_NO3']
COEFF_NH3N_NH3 = ATOMIC_WEIGHT_CONVERSIONS['Conv_Mol_NH3N_NH3']
COEFF_NOXN_NOX = ATOMIC_WEIGHT_CONVERSIONS['Conv_Mol_NON_NO']
