[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "pyproject-devenv"
version = "0.1.0"
description = "Create virtual environments using pyproject.toml metadata."
readme = "README.rst"
keywords = [ "pyproject", "toml", "virtualenv",]
dynamic = []
dependencies = [
    "click>=7.1.2",
    "consolekit>=1.1.2",
    "dom-toml>=0.4.0",
    "domdf-python-tools>=2.9.0",
    "packaging>=20.9",
    "pyproject-parser>=0.2.0",
    "shippinglabel>=0.14.1",
    "typing-extensions>=3.7.4.3",
    "virtualenv>=20.4.3",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: System :: Archiving :: Packaging",
    "Typing :: Typed",
]
requires-python = ">=3.6"

[[project.authors]]
name = "Dominic Davis-Foster"
email = "dominic@davis-foster.co.uk"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/repo-helper/pyproject-devenv"
"Issue Tracker" = "https://github.com/repo-helper/pyproject-devenv/issues"
"Source Code" = "https://github.com/repo-helper/pyproject-devenv"
Documentation = "https://pyproject-devenv.readthedocs.io/en/latest"

[project.scripts]
pyproject-devenv = "pyproject_devenv.__main__:main"
devenv = "pyproject_devenv.__main__:main"

[tool.mkrecipe]
conda-channels = [ "repo-helper",]
extras = "all"
license-key = "MIT"
package = "pyproject_devenv"

[tool.whey]
base-classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Topic :: System :: Archiving :: Packaging",
    "Typing :: Typed",
]
python-versions = [ "3.6", "3.7", "3.8", "3.9",]
python-implementations = [ "CPython", "PyPy",]
platforms = [ "Windows", "macOS", "Linux",]
license-key = "MIT"
package = "pyproject_devenv"
