[build-system]
requires = [
    "packaging==20.5; platform_machine=='arm64'",  # macos M1
    "setuptools",
    "wheel",
    "Cython>=0.29.22,<3.0",  # Note: keep in sync with tools/cythonize.py
    "numpy==1.16.6; python_version<='3.7'",
    "numpy==1.17.5; python_version=='3.8'",
    "numpy==1.19.5; python_version=='3.9'",
    "numpy; python_version>='3.10'",
    "numpy>=1.14"
]
