
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-24T08:08:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8450fe971369e4d1de31353beeff4e412efd9d37",
 "version": "2021.04.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
