
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-26T12:28:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "68c8c714be3da24d8983b32d82ef5fbcae943bdd",
 "version": "2.6.0-alpha.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
