[tool.poetry]
name = "ReCAP-Argument-Graph"
version = "0.1.41"
description = "A library for loading argument graphs in various formats (e.g., AIF)."
authors = ["Mirko Lenz <info@mirko-lenz.de>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "http://recap.uni-trier.de"
repository = "https://github.com/ReCAP-UTR/Argument-Graph"
documentation = "https://recap-argument-graph.readthedocs.io/en/latest"

[tool.poetry.dependencies]
python = "^3.8"
networkx = "^2.4"
pendulum = "^2.0"
graphviz = "^0.13.2"
lxml = "^4.4.2"
sphinx = { version = "^3.5", optional = true }
sphinx-autodoc-typehints = { version = "^1.11", optional = true }
sphinx-rtd-theme = { version = "^0.5.2", optional = true }
myst-parser = { version = "^0.13.7", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-datadir = "^1.3.1"
deepdiff = { extras = ["murmur"], version = "^4.0.9" }

[tool.poetry.extras]
docs = ["sphinx", "sphinx-autodoc-typehints", "sphinx-rtd-theme", "myst-parser"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
