[tool.poetry]
name = "pkce_flow"
version = "0.1.2"
description = "A utility for obtaining access tokens using the PKCE-enhanced authorization code flow (Oauth)"
authors = [
    "Mfon Eti-mfon <mfonetimfon@gmail.com>"
]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/a-thousand-juniors/pkce-flow"
repository = "https://gitlab.com/a-thousand-juniors/pkce-flow"
keywords = ["oauth", "pkce"]
classifiers = [
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
requests = "^2.25.1"
requests-mock = "^1.8.0"
click = "^7.1.2"

[tool.poetry.scripts]
test = "scripts:test"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
