# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rtloc.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RTLOC(object):
    def setupUi(self, RTLOC):
        RTLOC.setObjectName("RTLOC")
        RTLOC.resize(841, 656)
        self.centralwidget = QtWidgets.QWidget(RTLOC)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAnchors = QtWidgets.QPushButton(self.centralwidget)
        self.btnAnchors.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAnchors.sizePolicy().hasHeightForWidth())
        self.btnAnchors.setSizePolicy(sizePolicy)
        self.btnAnchors.setStyleSheet("width: 200px")
        self.btnAnchors.setObjectName("btnAnchors")
        self.horizontalLayout.addWidget(self.btnAnchors)
        self.btnTags = QtWidgets.QPushButton(self.centralwidget)
        self.btnTags.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTags.sizePolicy().hasHeightForWidth())
        self.btnTags.setSizePolicy(sizePolicy)
        self.btnTags.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnTags.setStyleSheet("width: 200px")
        self.btnTags.setObjectName("btnTags")
        self.horizontalLayout.addWidget(self.btnTags)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plotGrid = QtWidgets.QGridLayout()
        self.plotGrid.setObjectName("plotGrid")
        self.horizontalLayout_2.addLayout(self.plotGrid)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.anchorsList = QtWidgets.QTextEdit(self.centralwidget)
        self.anchorsList.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anchorsList.sizePolicy().hasHeightForWidth())
        self.anchorsList.setSizePolicy(sizePolicy)
        self.anchorsList.setObjectName("anchorsList")
        self.verticalLayout_3.addWidget(self.anchorsList)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.tagsList = QtWidgets.QTextEdit(self.centralwidget)
        self.tagsList.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsList.sizePolicy().hasHeightForWidth())
        self.tagsList.setSizePolicy(sizePolicy)
        self.tagsList.setObjectName("tagsList")
        self.verticalLayout_3.addWidget(self.tagsList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        RTLOC.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RTLOC)
        self.statusbar.setObjectName("statusbar")
        RTLOC.setStatusBar(self.statusbar)

        self.retranslateUi(RTLOC)
        QtCore.QMetaObject.connectSlotsByName(RTLOC)

    def retranslateUi(self, RTLOC):
        _translate = QtCore.QCoreApplication.translate
        RTLOC.setWindowTitle(_translate("RTLOC", "RTLOC"))
        self.btnAnchors.setText(_translate("RTLOC", "Start positioning anchors"))
        self.btnTags.setText(_translate("RTLOC", "Start positioning tags"))
        self.label.setText(_translate("RTLOC", "Anchors"))
        self.label_2.setText(_translate("RTLOC", "Tags"))
