# coding: utf-8

"""
    Agilicus API

    Agilicus API endpoints  # noqa: E501

    The version of the OpenAPI document: 2021.04.22
    Contact: dev@agilicus.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from agilicus_api.configuration import Configuration


class ListUpstreamGroupMapping(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'upstream_group_mapping': 'list[UpstreamGroupMapping]',
        'limit': 'int'
    }

    attribute_map = {
        'upstream_group_mapping': 'upstream_group_mapping',
        'limit': 'limit'
    }

    def __init__(self, upstream_group_mapping=None, limit=None, local_vars_configuration=None):  # noqa: E501
        """ListUpstreamGroupMapping - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._upstream_group_mapping = None
        self._limit = None
        self.discriminator = None

        self.upstream_group_mapping = upstream_group_mapping
        self.limit = limit

    @property
    def upstream_group_mapping(self):
        """Gets the upstream_group_mapping of this ListUpstreamGroupMapping.  # noqa: E501

        List of upstream group mapping for a given issuer  # noqa: E501

        :return: The upstream_group_mapping of this ListUpstreamGroupMapping.  # noqa: E501
        :rtype: list[UpstreamGroupMapping]
        """
        return self._upstream_group_mapping

    @upstream_group_mapping.setter
    def upstream_group_mapping(self, upstream_group_mapping):
        """Sets the upstream_group_mapping of this ListUpstreamGroupMapping.

        List of upstream group mapping for a given issuer  # noqa: E501

        :param upstream_group_mapping: The upstream_group_mapping of this ListUpstreamGroupMapping.  # noqa: E501
        :type: list[UpstreamGroupMapping]
        """
        if self.local_vars_configuration.client_side_validation and upstream_group_mapping is None:  # noqa: E501
            raise ValueError("Invalid value for `upstream_group_mapping`, must not be `None`")  # noqa: E501

        self._upstream_group_mapping = upstream_group_mapping

    @property
    def limit(self):
        """Gets the limit of this ListUpstreamGroupMapping.  # noqa: E501

        Limit of upstream group mappings in the response  # noqa: E501

        :return: The limit of this ListUpstreamGroupMapping.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this ListUpstreamGroupMapping.

        Limit of upstream group mappings in the response  # noqa: E501

        :param limit: The limit of this ListUpstreamGroupMapping.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and limit is None:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501

        self._limit = limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListUpstreamGroupMapping):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListUpstreamGroupMapping):
            return True

        return self.to_dict() != other.to_dict()
