
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-22T00:09:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4fa245f77912dfdfd613c84fb75f631c0b73f03",
 "version": "0.13.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
