
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-22T14:44:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fcb0b4baac89817bccae06cabc71dd0b5f0e08ef",
 "version": "1.10.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
