[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 80
skip-magic-trailing-comma = true
target-version = ["py38"]


[tool.isort]
atomic = true
force_single_line = true
line_length = 80
lines_after_imports = 2
profile = "black"
remove_redundant_aliases = true
skip_gitignore = true
src_paths = ["src"]
virtual_env = ".venv/bin/python"


[tool.poetry]
name = "dycw-pre-commit-hooks"
version = "0.2.24"
description = "My pre-commit hooks"
authors = ["Derek Wan <d.wan@icloud.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
frozendict = "^1.2"
gitpython = "^3.1.15"
loguru = "^0.5.3"
more-itertools = "^8.7.0"
pyyaml = "^5.4.1"
toml = "^0.10"

[tool.poetry.dev-dependencies]
pre-commit = "^2.12.1"
pytest = "^6.2.3"
pytest-randomly = "^3.7.0"
pytest-xdist = "^2.2.1"

[tool.poetry.scripts]
check-settings = "dycw_pre_commit_hooks.check_settings:main"


[tool.pytest.ini_options]
addopts = ["-q", "-rsxX", "--color=yes", "--strict-markers"]
minversion = 6.0
looponfailroots = ["src"]
testpaths = ["src/tests"]
xfail_strict = true

log_level = "WARNING"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_format = """\
  [%(asctime)s.%(msecs)03d] [%(levelno)d] [%(name)s:%(funcName)s] \
  [%(process)d]\n%(msg)s"""
log_cli_level = "WARNING"
