
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-21T11:42:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c302810b0d3fbc87bb1aa536709ce408842601ce",
 "version": "v0.5.3rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
