
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1ff2f47fa11c577d9158f98f15e09829c5710abf",
 "version": "0.5.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
