[tool.poetry]
name = "random-quote-generator-132190312"
version = "0.1.0"
description = ""
authors = ["Santhin <psierkin@gmail.com>"]
packages = [
    { include = "random_quote_generator" },
]

[tool.poetry.dependencies]
python = ">3.7,<4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
black = "^20.8b1"
isort = "^5.8.0"
flake8 = "^3.9.1"
bandit = "^1.7.0"
safety = "^1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


