# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 3.8

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/xraylarch
    - export PATH="$HOME/xraylarch/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge
    - conda info -a

install:
    - conda create -q -n xlarch python=3.8 numpy scipy matplotlib h5py scikit-learn cython pillow pandas
    - source activate xlarch
    - conda install scikit-image sqlalchemy psutil pytest pyyaml psycopg2 pyfai silx numdifftools emcee tomopy wxpython
    - pip install lmfit peakutils pyepics pyshortcuts termcolor sphinx dill pycifrw xraydb wxmplot wxutils
    - python setup.py install

script:
    - cd tests
    - pytest
