kind: MasterConfigSupplier
id: sdk.supplier.master_config.default_vars
field_key: default_vars

---

kind: MasterConfigSupplier
id: sdk.supplier.master_config.vendor_injection_vars
field_key: vendor_injection_vars

---

kind: MasterConfigSupplier
id: sdk.supplier.master_config.user_injection_vars
field_key: user_injection_vars

---

kind: MasterConfigSupplier
id: sdk.supplier.master_config.user_vars
field_key: user_vars

---

kind: MasterConfigSupplier
id: sdk.supplier.master_config.prefs
field_key: prefs

---

kind: MasterConfigSupplier
id: sdk.supplier.master_config.ns
field_key: ns

---

kind: MergeSupplier
id: sdk.supplier.master_config.variables
source:
  - get::sdk.supplier.master_config.default_vars
  - get::sdk.supplier.master_config.vendor_injection_vars
  - get::sdk.supplier.master_config.user_injection_vars
  - get::sdk.supplier.master_config.user_vars

---

kind: Supplier
id: sdk.supplier.injections_ktea
source:
  type: server
  uri: https://api.codesdk.com/services/ktea/nectar/vals2sec/1.0.0

---

kind: MasterConfigSupplier
id: sdk.supplier.master_config.ktea
field_key: ktea
