language: python
python:
  - 3.7
install:
  - sudo apt-get -y update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --append channels bioconda
  - conda config --append channels conda-forge
  - conda install pandas numpy scipy scikit-learn
  - conda install -c bioconda sra-tools
  - conda install -c bioconda meme=5.1.1
  - conda install -c bioconda bedtools homer star samtools pysam
  - conda install -c bioconda pybedtools
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION bedtools homer star samtools pysam sra-tools meme pandas numpy scipy scikit-learn pybedtools
  - conda activate test-environment
  - pip install nose codecov pathos
  - python setup.py install
script:
  - coverage run --source=inferelator_prior setup.py test
after_success:
  - codecov
after_failure:
  - python -c "import os; print(repr(os.name))"
  - pwd
  - find .
  - conda list