
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-26T07:43:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "50e90c5abb7ddc8c59179340184617bf306f76ab",
 "version": "0.7.0.post.dev84"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
