
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-21T21:27:30+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "e83c70349ad5e600dc5124b0d08b4769f5533afa",
 "version": "0.1.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
