[tool.poetry]
name = "waterdip"
version = "0.1.0"
description = "Waterdip Python SDK"
authors = ["Subhankar <suhankar@waterdip.ai>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"