# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dlxapi.configuration import Configuration


class PortfolioPlanUserUpdatedMessagePayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'portfolio_plan_user': 'PortfolioPlanUser'
    }

    attribute_map = {
        'portfolio_plan_user': 'portfolioPlanUser'
    }

    def __init__(self, portfolio_plan_user=None, _configuration=None):  # noqa: E501
        """PortfolioPlanUserUpdatedMessagePayload - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._portfolio_plan_user = None
        self.discriminator = None

        self.portfolio_plan_user = portfolio_plan_user

    @property
    def portfolio_plan_user(self):
        """Gets the portfolio_plan_user of this PortfolioPlanUserUpdatedMessagePayload.  # noqa: E501


        :return: The portfolio_plan_user of this PortfolioPlanUserUpdatedMessagePayload.  # noqa: E501
        :rtype: PortfolioPlanUser
        """
        return self._portfolio_plan_user

    @portfolio_plan_user.setter
    def portfolio_plan_user(self, portfolio_plan_user):
        """Sets the portfolio_plan_user of this PortfolioPlanUserUpdatedMessagePayload.


        :param portfolio_plan_user: The portfolio_plan_user of this PortfolioPlanUserUpdatedMessagePayload.  # noqa: E501
        :type: PortfolioPlanUser
        """
        if self._configuration.client_side_validation and portfolio_plan_user is None:
            raise ValueError("Invalid value for `portfolio_plan_user`, must not be `None`")  # noqa: E501

        self._portfolio_plan_user = portfolio_plan_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PortfolioPlanUserUpdatedMessagePayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PortfolioPlanUserUpdatedMessagePayload):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PortfolioPlanUserUpdatedMessagePayload):
            return True

        return self.to_dict() != other.to_dict()
