# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dlxapi.configuration import Configuration


class ProjectAttachmentRemovedEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attachment_size': 'int',
        'portfolio_id': 'str',
        'name': 'str',
        'attachment_name': 'str',
        'id': 'str',
        'attachment_id': 'str',
        'portfolio_plan': 'PortfolioPlan'
    }

    attribute_map = {
        'attachment_size': 'attachmentSize',
        'portfolio_id': 'portfolioId',
        'name': 'name',
        'attachment_name': 'attachmentName',
        'id': 'id',
        'attachment_id': 'attachmentId',
        'portfolio_plan': 'portfolioPlan'
    }

    def __init__(self, attachment_size=None, portfolio_id=None, name=None, attachment_name=None, id=None, attachment_id=None, portfolio_plan=None, _configuration=None):  # noqa: E501
        """ProjectAttachmentRemovedEvent - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._attachment_size = None
        self._portfolio_id = None
        self._name = None
        self._attachment_name = None
        self._id = None
        self._attachment_id = None
        self._portfolio_plan = None
        self.discriminator = None

        if attachment_size is not None:
            self.attachment_size = attachment_size
        if portfolio_id is not None:
            self.portfolio_id = portfolio_id
        if name is not None:
            self.name = name
        if attachment_name is not None:
            self.attachment_name = attachment_name
        if id is not None:
            self.id = id
        if attachment_id is not None:
            self.attachment_id = attachment_id
        if portfolio_plan is not None:
            self.portfolio_plan = portfolio_plan

    @property
    def attachment_size(self):
        """Gets the attachment_size of this ProjectAttachmentRemovedEvent.  # noqa: E501


        :return: The attachment_size of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :rtype: int
        """
        return self._attachment_size

    @attachment_size.setter
    def attachment_size(self, attachment_size):
        """Sets the attachment_size of this ProjectAttachmentRemovedEvent.


        :param attachment_size: The attachment_size of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :type: int
        """

        self._attachment_size = attachment_size

    @property
    def portfolio_id(self):
        """Gets the portfolio_id of this ProjectAttachmentRemovedEvent.  # noqa: E501


        :return: The portfolio_id of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :rtype: str
        """
        return self._portfolio_id

    @portfolio_id.setter
    def portfolio_id(self, portfolio_id):
        """Sets the portfolio_id of this ProjectAttachmentRemovedEvent.


        :param portfolio_id: The portfolio_id of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :type: str
        """

        self._portfolio_id = portfolio_id

    @property
    def name(self):
        """Gets the name of this ProjectAttachmentRemovedEvent.  # noqa: E501


        :return: The name of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectAttachmentRemovedEvent.


        :param name: The name of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def attachment_name(self):
        """Gets the attachment_name of this ProjectAttachmentRemovedEvent.  # noqa: E501


        :return: The attachment_name of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :rtype: str
        """
        return self._attachment_name

    @attachment_name.setter
    def attachment_name(self, attachment_name):
        """Sets the attachment_name of this ProjectAttachmentRemovedEvent.


        :param attachment_name: The attachment_name of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :type: str
        """

        self._attachment_name = attachment_name

    @property
    def id(self):
        """Gets the id of this ProjectAttachmentRemovedEvent.  # noqa: E501


        :return: The id of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProjectAttachmentRemovedEvent.


        :param id: The id of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def attachment_id(self):
        """Gets the attachment_id of this ProjectAttachmentRemovedEvent.  # noqa: E501


        :return: The attachment_id of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :rtype: str
        """
        return self._attachment_id

    @attachment_id.setter
    def attachment_id(self, attachment_id):
        """Sets the attachment_id of this ProjectAttachmentRemovedEvent.


        :param attachment_id: The attachment_id of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :type: str
        """

        self._attachment_id = attachment_id

    @property
    def portfolio_plan(self):
        """Gets the portfolio_plan of this ProjectAttachmentRemovedEvent.  # noqa: E501


        :return: The portfolio_plan of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :rtype: PortfolioPlan
        """
        return self._portfolio_plan

    @portfolio_plan.setter
    def portfolio_plan(self, portfolio_plan):
        """Sets the portfolio_plan of this ProjectAttachmentRemovedEvent.


        :param portfolio_plan: The portfolio_plan of this ProjectAttachmentRemovedEvent.  # noqa: E501
        :type: PortfolioPlan
        """

        self._portfolio_plan = portfolio_plan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectAttachmentRemovedEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectAttachmentRemovedEvent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectAttachmentRemovedEvent):
            return True

        return self.to_dict() != other.to_dict()
