# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dlxapi.configuration import Configuration


class ValueInsights(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'likert_scale_field_insights': 'list[LikertScaleFieldInsight]'
    }

    attribute_map = {
        'likert_scale_field_insights': 'likertScaleFieldInsights'
    }

    def __init__(self, likert_scale_field_insights=None, _configuration=None):  # noqa: E501
        """ValueInsights - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._likert_scale_field_insights = None
        self.discriminator = None

        if likert_scale_field_insights is not None:
            self.likert_scale_field_insights = likert_scale_field_insights

    @property
    def likert_scale_field_insights(self):
        """Gets the likert_scale_field_insights of this ValueInsights.  # noqa: E501


        :return: The likert_scale_field_insights of this ValueInsights.  # noqa: E501
        :rtype: list[LikertScaleFieldInsight]
        """
        return self._likert_scale_field_insights

    @likert_scale_field_insights.setter
    def likert_scale_field_insights(self, likert_scale_field_insights):
        """Sets the likert_scale_field_insights of this ValueInsights.


        :param likert_scale_field_insights: The likert_scale_field_insights of this ValueInsights.  # noqa: E501
        :type: list[LikertScaleFieldInsight]
        """

        self._likert_scale_field_insights = likert_scale_field_insights

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValueInsights, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValueInsights):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ValueInsights):
            return True

        return self.to_dict() != other.to_dict()
