# coding: utf-8

"""
    Agilicus API

    Agilicus API endpoints  # noqa: E501

    The version of the OpenAPI document: 2021.04.28
    Contact: dev@agilicus.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import agilicus_api
from agilicus_api.models.generic_int_metric import GenericIntMetric  # noqa: E501
from agilicus_api.rest import ApiException

class TestGenericIntMetric(unittest.TestCase):
    """GenericIntMetric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GenericIntMetric
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = agilicus_api.models.generic_int_metric.GenericIntMetric()  # noqa: E501
        if include_optional :
            return GenericIntMetric(
                name = 'gc_pauses_histogram_1.0', 
                value = 678382
            )
        else :
            return GenericIntMetric(
                name = 'gc_pauses_histogram_1.0',
                value = 678382,
        )

    def testGenericIntMetric(self):
        """Test GenericIntMetric"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
