# Generated by Django 3.2 on 2021-04-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kesha", "0002_booking_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="text",
        ),
        migrations.AddField(
            model_name="booking",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
