# Generated by Django 3.2 on 2021-04-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kesha", "0004_auto_20210425_0332"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_parents",
                to="kesha.parent",
            ),
        ),
    ]
