[tool.poetry]
name = "tikotapi"
version = "1.0.6"
description = "The lib for game published in tikotshopgame.tk. tikotapien.tk. tikotapi.version()"
authors = ["tikotstudio <tikotstudio@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
