
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-25T21:26:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdf71076938a3ab069325a8608b218e22a080d61",
 "version": "2.6.0-alpha.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
