
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-26T10:35:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "84f511f4a9b4686390214de545ee9e23565af932",
 "version": "0.1.1.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
