[tool]
[tool.poetry]
name = "yaxit"
version = "0.1.0"
homepage = "https://github.com/jmosbacher/yaxit"
description = "Top-level package for yaxit."
authors = ["Yossi Mosbacher <joe.mosbacher@gmail.com>"]
readme = "README.rst"
license =  "MIT"
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
]
packages = [
    { include = "yaxit" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.7.1"
click = "*"
pandas = "^1.2.4"
h5py = "^3.2.1"
xarray = "^0.17.0"
pathlib = "^1.0.1"
xpublish = "^0.1.0"
matplotlib = "^3.4.1"
bokeh = "^2.3.1"
aiohttp = "^3.7.4"
requests = "^2.25.1"
tables = "^3.6.1"
numpy = "^1.20.2"
xrviz = "^0.1.4"

[tool.poetry.dev-dependencies]
bumpversion = "*"
coverage = "*"
flake8 = "*"
isort = "*"
pylint = "*"
dephell = "*"
pytest = "*"
sphinx = "*"
tox = "*"
yapf = "*"
sphinx-material = "*"
nbsphinx = "*"

[tool.poetry.scripts]
yaxit = 'yaxit.cli:main'

[build-system]
requires = ["poetry>=0.12", "setuptools"]
build-backend = "poetry.masonry.api"

[tool.dephell.main]
versioning = "semver"
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
