
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-27T13:21:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3d2d0036d8a9b8cfc6bad391a7545dc550cce79",
 "version": "1.20.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
