
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-27T17:53:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "feb3a334b7bbf302b13a6da80e0b022a4cf75a4e",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
