[tool.poetry]
name = "mcp-api"
version = "0.1.2"
description = "A small unofficial Wrapper for the Minecraft game Profiles API."
authors = ["Julheer <admin0x12@julheer.ru>"]
license = "MIT"
packages = [{include "mcp-api.py"}]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
