# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2021-04-22 14:22:27.942280
__version__ = '3.1.0'