[tool.poetry]
name = "graphic-coloring-engine"
version = "0.1.0"
description = ""
authors = ["filosfino <github@filosfino.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.10"
sympy = "^1.8"
Shapely = "^1.7.1"
colormath = "^3.0.0"
pydash = "^5.0.0"
typing-extensions = "^3.7.4"
Pillow = "^8.2.0"
cached-property = "^1.5.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.1"
pytest = "^6.2.3"
snapshottest = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.doubanio.com/simple/"
default = true
