# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dlxapi.configuration import Configuration


class FieldValues(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'items': 'list[FieldValue]',
        'collection_info': 'FieldValuesCollectionInfo'
    }

    attribute_map = {
        'items': 'items',
        'collection_info': 'collectionInfo'
    }

    def __init__(self, items=None, collection_info=None, _configuration=None):  # noqa: E501
        """FieldValues - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._items = None
        self._collection_info = None
        self.discriminator = None

        if items is not None:
            self.items = items
        if collection_info is not None:
            self.collection_info = collection_info

    @property
    def items(self):
        """Gets the items of this FieldValues.  # noqa: E501


        :return: The items of this FieldValues.  # noqa: E501
        :rtype: list[FieldValue]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this FieldValues.


        :param items: The items of this FieldValues.  # noqa: E501
        :type: list[FieldValue]
        """

        self._items = items

    @property
    def collection_info(self):
        """Gets the collection_info of this FieldValues.  # noqa: E501


        :return: The collection_info of this FieldValues.  # noqa: E501
        :rtype: FieldValuesCollectionInfo
        """
        return self._collection_info

    @collection_info.setter
    def collection_info(self, collection_info):
        """Sets the collection_info of this FieldValues.


        :param collection_info: The collection_info of this FieldValues.  # noqa: E501
        :type: FieldValuesCollectionInfo
        """

        self._collection_info = collection_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FieldValues, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FieldValues):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FieldValues):
            return True

        return self.to_dict() != other.to_dict()
