# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dlxapi.configuration import Configuration


class IdeaFormFieldRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'portfolio_id': 'str',
        'field_ids': 'list[str]',
        'field_types': 'list[FieldType]',
        'is_included': 'bool',
        'is_required': 'bool',
        'idea_field_position': 'int'
    }

    attribute_map = {
        'portfolio_id': 'portfolioId',
        'field_ids': 'fieldIds',
        'field_types': 'fieldTypes',
        'is_included': 'isIncluded',
        'is_required': 'isRequired',
        'idea_field_position': 'ideaFieldPosition'
    }

    def __init__(self, portfolio_id=None, field_ids=None, field_types=None, is_included=None, is_required=None, idea_field_position=None, _configuration=None):  # noqa: E501
        """IdeaFormFieldRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._portfolio_id = None
        self._field_ids = None
        self._field_types = None
        self._is_included = None
        self._is_required = None
        self._idea_field_position = None
        self.discriminator = None

        if portfolio_id is not None:
            self.portfolio_id = portfolio_id
        if field_ids is not None:
            self.field_ids = field_ids
        if field_types is not None:
            self.field_types = field_types
        if is_included is not None:
            self.is_included = is_included
        if is_required is not None:
            self.is_required = is_required
        if idea_field_position is not None:
            self.idea_field_position = idea_field_position

    @property
    def portfolio_id(self):
        """Gets the portfolio_id of this IdeaFormFieldRequest.  # noqa: E501


        :return: The portfolio_id of this IdeaFormFieldRequest.  # noqa: E501
        :rtype: str
        """
        return self._portfolio_id

    @portfolio_id.setter
    def portfolio_id(self, portfolio_id):
        """Sets the portfolio_id of this IdeaFormFieldRequest.


        :param portfolio_id: The portfolio_id of this IdeaFormFieldRequest.  # noqa: E501
        :type: str
        """

        self._portfolio_id = portfolio_id

    @property
    def field_ids(self):
        """Gets the field_ids of this IdeaFormFieldRequest.  # noqa: E501


        :return: The field_ids of this IdeaFormFieldRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._field_ids

    @field_ids.setter
    def field_ids(self, field_ids):
        """Sets the field_ids of this IdeaFormFieldRequest.


        :param field_ids: The field_ids of this IdeaFormFieldRequest.  # noqa: E501
        :type: list[str]
        """

        self._field_ids = field_ids

    @property
    def field_types(self):
        """Gets the field_types of this IdeaFormFieldRequest.  # noqa: E501


        :return: The field_types of this IdeaFormFieldRequest.  # noqa: E501
        :rtype: list[FieldType]
        """
        return self._field_types

    @field_types.setter
    def field_types(self, field_types):
        """Sets the field_types of this IdeaFormFieldRequest.


        :param field_types: The field_types of this IdeaFormFieldRequest.  # noqa: E501
        :type: list[FieldType]
        """

        self._field_types = field_types

    @property
    def is_included(self):
        """Gets the is_included of this IdeaFormFieldRequest.  # noqa: E501


        :return: The is_included of this IdeaFormFieldRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_included

    @is_included.setter
    def is_included(self, is_included):
        """Sets the is_included of this IdeaFormFieldRequest.


        :param is_included: The is_included of this IdeaFormFieldRequest.  # noqa: E501
        :type: bool
        """

        self._is_included = is_included

    @property
    def is_required(self):
        """Gets the is_required of this IdeaFormFieldRequest.  # noqa: E501


        :return: The is_required of this IdeaFormFieldRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_required

    @is_required.setter
    def is_required(self, is_required):
        """Sets the is_required of this IdeaFormFieldRequest.


        :param is_required: The is_required of this IdeaFormFieldRequest.  # noqa: E501
        :type: bool
        """

        self._is_required = is_required

    @property
    def idea_field_position(self):
        """Gets the idea_field_position of this IdeaFormFieldRequest.  # noqa: E501


        :return: The idea_field_position of this IdeaFormFieldRequest.  # noqa: E501
        :rtype: int
        """
        return self._idea_field_position

    @idea_field_position.setter
    def idea_field_position(self, idea_field_position):
        """Sets the idea_field_position of this IdeaFormFieldRequest.


        :param idea_field_position: The idea_field_position of this IdeaFormFieldRequest.  # noqa: E501
        :type: int
        """

        self._idea_field_position = idea_field_position

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IdeaFormFieldRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdeaFormFieldRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IdeaFormFieldRequest):
            return True

        return self.to_dict() != other.to_dict()
