# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dlxapi.configuration import Configuration


class PortfolioPlanGrades(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'items': 'list[PortfolioPlanGrade]',
        'portfolio': 'Portfolio',
        'details': 'list[PortfolioPlanGrades]',
        'grading_type': 'GradingType'
    }

    attribute_map = {
        'items': 'items',
        'portfolio': 'portfolio',
        'details': 'details',
        'grading_type': 'gradingType'
    }

    def __init__(self, items=None, portfolio=None, details=None, grading_type=None, _configuration=None):  # noqa: E501
        """PortfolioPlanGrades - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._items = None
        self._portfolio = None
        self._details = None
        self._grading_type = None
        self.discriminator = None

        if items is not None:
            self.items = items
        if portfolio is not None:
            self.portfolio = portfolio
        if details is not None:
            self.details = details
        if grading_type is not None:
            self.grading_type = grading_type

    @property
    def items(self):
        """Gets the items of this PortfolioPlanGrades.  # noqa: E501


        :return: The items of this PortfolioPlanGrades.  # noqa: E501
        :rtype: list[PortfolioPlanGrade]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this PortfolioPlanGrades.


        :param items: The items of this PortfolioPlanGrades.  # noqa: E501
        :type: list[PortfolioPlanGrade]
        """

        self._items = items

    @property
    def portfolio(self):
        """Gets the portfolio of this PortfolioPlanGrades.  # noqa: E501


        :return: The portfolio of this PortfolioPlanGrades.  # noqa: E501
        :rtype: Portfolio
        """
        return self._portfolio

    @portfolio.setter
    def portfolio(self, portfolio):
        """Sets the portfolio of this PortfolioPlanGrades.


        :param portfolio: The portfolio of this PortfolioPlanGrades.  # noqa: E501
        :type: Portfolio
        """

        self._portfolio = portfolio

    @property
    def details(self):
        """Gets the details of this PortfolioPlanGrades.  # noqa: E501


        :return: The details of this PortfolioPlanGrades.  # noqa: E501
        :rtype: list[PortfolioPlanGrades]
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this PortfolioPlanGrades.


        :param details: The details of this PortfolioPlanGrades.  # noqa: E501
        :type: list[PortfolioPlanGrades]
        """

        self._details = details

    @property
    def grading_type(self):
        """Gets the grading_type of this PortfolioPlanGrades.  # noqa: E501


        :return: The grading_type of this PortfolioPlanGrades.  # noqa: E501
        :rtype: GradingType
        """
        return self._grading_type

    @grading_type.setter
    def grading_type(self, grading_type):
        """Sets the grading_type of this PortfolioPlanGrades.


        :param grading_type: The grading_type of this PortfolioPlanGrades.  # noqa: E501
        :type: GradingType
        """

        self._grading_type = grading_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PortfolioPlanGrades, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PortfolioPlanGrades):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PortfolioPlanGrades):
            return True

        return self.to_dict() != other.to_dict()
