# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dlxapi.configuration import Configuration


class TimeInterval(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_month': 'int',
        'type': 'TimePeriodType'
    }

    attribute_map = {
        'start_month': 'startMonth',
        'type': 'type'
    }

    def __init__(self, start_month=None, type=None, _configuration=None):  # noqa: E501
        """TimeInterval - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._start_month = None
        self._type = None
        self.discriminator = None

        if start_month is not None:
            self.start_month = start_month
        if type is not None:
            self.type = type

    @property
    def start_month(self):
        """Gets the start_month of this TimeInterval.  # noqa: E501


        :return: The start_month of this TimeInterval.  # noqa: E501
        :rtype: int
        """
        return self._start_month

    @start_month.setter
    def start_month(self, start_month):
        """Sets the start_month of this TimeInterval.


        :param start_month: The start_month of this TimeInterval.  # noqa: E501
        :type: int
        """

        self._start_month = start_month

    @property
    def type(self):
        """Gets the type of this TimeInterval.  # noqa: E501


        :return: The type of this TimeInterval.  # noqa: E501
        :rtype: TimePeriodType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TimeInterval.


        :param type: The type of this TimeInterval.  # noqa: E501
        :type: TimePeriodType
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimeInterval, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeInterval):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TimeInterval):
            return True

        return self.to_dict() != other.to_dict()
