[tool.poetry]
name = "response_differ"
version = "0.1.0"
description = ""
authors = ["vkytepov <vkytepov@live.com>"]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^5.4.1"
requests = "^2.25.1"
deepdiff = "^5.3.0"
click = "^7.1.2"
vcrpy = "^4.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
run = "differ.cli:run"
