[tool.poetry]
name = "ikutsu"
version = "0.1.1"
description = ""
authors = ["Hirokazu Hirono <hirono.hirokazu@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fire = "^0.4.0"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ikutsu = "ikutsu.ikutsu:main"