
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-22T18:24:35+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "216f611d25349e9c17503f0267b4a5c8d6f91d81",
 "version": "2.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
