[tool.poetry]
name = "grilled-algorithm"
version = "0.1.8"
description = ""
authors = ["hans <dxzenghan@163.com>"]
packages = [
    { include = "grilled", from = "src" }
]

[[tool.poetry.source]]
name = "tuna-tsinghua"
default = false
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"

[tool.poetry.dependencies]
python = "^3.7"
grilled-common = "^0.2.1"
pandas = "^1.2.3"
python-dotenv = "^0.16.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
