# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from dlxapi.api_client import ApiClient


class MessageTokensApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_message_token(self, destination_type, **kwargs):  # noqa: E501
        """Get message authorization token for a destination  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_message_token(destination_type, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object destination_type: Message destination type (required)
        :param str portfolio_id: Portfolio id for PORTFOLIO destination type
        :param str portfolio_plan_id: Portfolio plan id for PORTFOLIOPLAN destination type
        :return: MessageToken
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_message_token_with_http_info(destination_type, **kwargs)  # noqa: E501
        else:
            (data) = self.get_message_token_with_http_info(destination_type, **kwargs)  # noqa: E501
            return data

    def get_message_token_with_http_info(self, destination_type, **kwargs):  # noqa: E501
        """Get message authorization token for a destination  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_message_token_with_http_info(destination_type, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object destination_type: Message destination type (required)
        :param str portfolio_id: Portfolio id for PORTFOLIO destination type
        :param str portfolio_plan_id: Portfolio plan id for PORTFOLIOPLAN destination type
        :return: MessageToken
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['destination_type', 'portfolio_id', 'portfolio_plan_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_message_token" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'destination_type' is set
        if self.api_client.client_side_validation and ('destination_type' not in params or
                                                       params['destination_type'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `destination_type` when calling `get_message_token`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'destination_type' in params:
            query_params.append(('destinationType', params['destination_type']))  # noqa: E501
        if 'portfolio_id' in params:
            query_params.append(('portfolioId', params['portfolio_id']))  # noqa: E501
        if 'portfolio_plan_id' in params:
            query_params.append(('portfolioPlanId', params['portfolio_plan_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['OAuth2']  # noqa: E501

        return self.api_client.call_api(
            '/messageTokens', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MessageToken',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
