parameters:
  datalake:
    base_path: '/foo/bar'

  pysparkbundle:
    filesystem: dummy_filesystem

  datalakebundle:
    table:
      name_template: '%kernel.environment%_{identifier}'
      defaults:
        encrypted: !expr 'db_identifier[-1:] == "e"'
        db_identifier_base: !expr 'db_identifier[:db_identifier.find("_")]'
        target_path:
          resolver_class: 'datalakebundle.test.TargetPathResolver'
          resolver_arguments:
            - '%datalake.base_path%'

    tables:
      mydatabase_e.my_table:
        schema_loader: 'datalakebundle.test.TestSchema:get_schema'

      mydatabase_p.another_table:
        schema_loader: 'datalakebundle.test.AnotherSchema:get_schema'
        partition_by: ['date']

services:
  datalakebundle.test.DummySparkFactory:

  pyspark.sql.session.SparkSession:
    factory: ['@datalakebundle.test.DummySparkFactory', 'create']

  pysparkbundle.filesystem.DummyFilesystem:
    tags:
      - {name: 'pysparkbundle.filesystem', alias: dummy_filesystem}
