parameters:
  datalakebundle:
    notebook:
      module_template: '%daipe.root_module.name%.{db_identifier}.{table_identifier}.{table_identifier}'
      display:
        enabled: True
      duplicate_columns_check:
        enabled: True
    table:
      name_template: '%kernel.environment%_{identifier}'
      schema:
        loader_template: '{notebook_parent_module}.schema:get_schema'
      defaults:
        notebook_module:
          resolver_class: 'datalakebundle.notebook.NotebookModuleResolver'
          resolver_arguments:
            - '%datalakebundle.notebook.module_template%'
        schema_loader:
          resolver_class: 'datalakebundle.table.schema.SchemaLoaderResolver'
          resolver_arguments:
            - '%datalakebundle.table.schema.loader_template%'
    tables:

services:
  datalakebundle.logger: "@daipecore.logger"

  datalakebundle.notebook.decorator.DuplicateColumnsChecker:
    arguments:
      - '@datalakebundle.logger'

  datalakebundle.table.config.TableConfigParser:
    arguments:
      - '%datalakebundle.table.name_template%'

  datalakebundle.table.config.TableConfigManager:
    arguments:
      - '%datalakebundle.tables%'
      - '%datalakebundle.table.defaults%'

  datalakebundle.table.create.EmptyDataframeWriter:

  datalakebundle.table.create.TableCreator:
    arguments:
      - '@datalakebundle.logger'

  datalakebundle.table.create.TableCreatorCommand:
    tags:
      - 'console.command'

  datalakebundle.table.create.TableRecreator:
    arguments:
      - '@datalakebundle.logger'

  datalakebundle.table.create.TableRecreatorCommand:
    arguments:
      - '@datalakebundle.logger'
      - '@pysparkbundle.filesystem'
    tags:
      - 'console.command'

  datalakebundle.table.create.MissingTablesCreatorCommand:
    arguments:
      - '@datalakebundle.logger'
    tags:
      - 'console.command'

  datalakebundle.table.delete.TableDeleter:
    arguments:
      - '@datalakebundle.logger'
      - '@pysparkbundle.filesystem'

  datalakebundle.table.delete.TableDeleterCommand:
    arguments:
      - '@datalakebundle.logger'
    tags:
      - 'console.command'

  datalakebundle.table.optimize.TableOptimizerCommand:
    arguments:
      - '@datalakebundle.logger'
    tags:
      - 'console.command'

  datalakebundle.table.optimize.TablesOptimizerCommand:
    arguments:
      - '@datalakebundle.logger'
    tags:
      - 'console.command'

  datalakebundle.table.TableExistenceChecker:

  datalakebundle.table.TableManager:
    arguments:
      - '%datalakebundle.table.name_template%'
      - '@datalakebundle.logger'
      - '@pysparkbundle.filesystem'

  datalakebundle.table.TableWriter:
    arguments:
      - '@datalakebundle.logger'

  datalakebundle.table.upsert.UpsertQueryCreator:

  datalakebundle.table.identifier.IdentifierParser:
