[tool.poetry]
name = "tatuarvela-magic"
version = "3.0.0"
description = "A tool for simplifying repeated command line tasks"
authors = ["Tatu Arvela <tatu.arvela@nitor.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/TatuArvela/Magic"
packages = [
    {include = "magic"}
]

[tool.poetry.dependencies]
python = "^3.9"
docopt = "^0.6.2"
fastjsonschema = "^2.15.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
isort = "^5.7.0"
pytest = "^6.2.2"
pre-commit = "^2.11.1"
bandit = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
magic = "magic:main"

[tool.isort]
profile = "black"
skip_gitignore = true

[tool.pytest]
# Put something here
